### PR TITLE
Add support for Themed App Icons in Android 13

### PR DESCRIPTION
**Pull request by gnufella**

### CODE REVIEW

**Comment by gnufella** [comment]
Another variation using Proton's official greyscale logo for Mail.

### Light Mode:


### Dark Mode:

**Comment by ZoricaStojchevska** [comment]
Hello, the launcher icons are part of our design system and need to come from our Design team. Thank you for the suggestion and the understanding.

**Comment by Extravi** [comment]
good idea looks cool

**Comment by boomesh** [comment]
@ZoricaStojchevska sorry for commenting on a closed issue.  But I really think this should be revisited, the themed icons look great.

Right now the app socks out like a sore thumb, and looks really lackluster.

**Comment by Bungeetaco** [comment]
Please implement this

**Comment by wlowen** [comment]
Also chiming in that this should be implemented. Proton Mail is the one app on my home screen without a themed icon. It seems silly to reject this for the reason that it needs to come from the design team, especially since it hasn't been done in the six months since.

**Comment by M0-7** [comment]
I agree with @TwisX. The other proton suite apps like vpn and calendar have the same issue

**Comment by Extravi** [comment]
yeah I don't see any reason why this wouldn't be added

**Comment by Extravi** [comment]
I think it's worth taking a look at this again

**Comment by M0-7** [comment]
They previously said that the icons are from the design team and only they are able to change it. Where are you supposed to open an issue for this then?

**Comment by githububub** [comment]
This is far overdue as themed icons were introduced in A13. And as commented above: Proton Mail is the one app on my home screen without a themed icon. How do we get in touch with the design team to get the ball rolling?

**Comment by Extravi** [comment]
I noticed both proton pass and proton drive has it just not proton mail proton vpn or proton calendar

**Comment by asudox** [comment]
You know, my homescreen is about to be perfect.
But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.

**Comment by Extravi** [comment]
> You know, my homescreen is about to be perfect.
> But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.

I agree. Why does some proton apps have support for it and some don't what's going on?

**Comment by Extravi** [comment]
Proton Drive and Proton pass have native support for it just not Proton VPN, Proton Calendar and Proton Mail?

**Comment by asudox** [comment]
@ZoricaStojchevska Any news? Can we even contact the design team?

**Comment by M0-7** [comment]
> You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.

So true, anyone know the right place to raise an issue?

**Comment by asudox** [comment]
> > You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.
> 
> So true, anyone know the right place to raise an issue?

Probably their official forum.
They post feature requests there: https://protonmail.uservoice.com/

Though it seems like the team barely responds in the Proton Mail section. Makes me wonder if they even care about the android app at this point.
Maybe switching to Proton Mail from Skiff was a wrong choice.

**Comment by Extravi** [comment]
they probably have different teams working on different applications and that's probably why there's inconsistency

**Comment by Extravi** [comment]
> > > You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.
> > 
> > So true, anyone know the right place to raise an issue?
> 
> Probably their official forum.
> They post feature requests there: https://protonmail.uservoice.com/
> 
> Though it seems like the team barely responds in the Proton Mail section. Makes me doubt if they even care about the android app at this point.
> Maybe switching to Proton Mail from Skiff was a wrong choice.

try making a post on Reddit maybe and point out that other proton apps have it enabled?

**Comment by asudox** [comment]
> > > > You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.
> > > 
> > > So true, anyone know the right place to raise an issue?
> > 
> > Probably their official forum.
> > They post feature requests there: https://protonmail.uservoice.com/
> > 
> > Though it seems like the team barely responds in the Proton Mail section. Makes me doubt if they even care about the android app at this point.
> > Maybe switching to Proton Mail from Skiff was a wrong choice.
> 
> try making a post on Reddit maybe and point out that other proton apps have it enabled?

Will try.

**Comment by M0-7** [comment]
> > > You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.
> > 
> > 
> > So true, anyone know the right place to raise an issue?
> 
> Probably their official forum. They post feature requests there: https://protonmail.uservoice.com/
> 
> Though it seems like the team barely responds in the Proton Mail section. Makes me wonder if they even care about the android app at this point. Maybe switching to Proton Mail from Skiff was a wrong choice.

That's unfortunate. The inconsistency in priorities between different apps and platforms is just sad :/.  Has anyone tried the beta app? Maybe that has themed icon supoort

**Comment by asudox** [comment]
> > > > You know, my homescreen is about to be perfect. But then, this app comes into it, and just disturbs everything. Even though closed, it would be real nice if they added this. It's not even hard to do.
> > > 
> > > 
> > > So true, anyone know the right place to raise an issue?
> > 
> > Probably their official forum. They post feature requests there: https://protonmail.uservoice.com/
> > 
> > Though it seems like the team barely responds in the Proton Mail section. Makes me wonder if they even care about the android app at this point. Maybe switching to Proton Mail from Skiff was a wrong choice.
> 
> That's unfortunate. The inconsistency in priorities between different apps and platforms is just sad :/.  Has anyone tried the beta app? Maybe that has themed icon supoort

I use it. No changes.

**Comment by Extravi** [comment]
i found this from a month ago https://www.reddit.com/r/ProtonMail/comments/195is7m/proton_team_please_fix_theme_icons/

**Comment by M0-7** [comment]
I guess we gotta just wait then

**Comment by asudox** [comment]
> i found this from a month ago https://www.reddit.com/r/ProtonMail/comments/195is7m/proton_team_please_fix_theme_icons/

Yeah indeed. The team has been looking into designing a Material You Icon for several months now. How hard. Even rewriting the whole app was easier.

**Comment by Extravi** [comment]
> > i found this from a month ago https://www.reddit.com/r/ProtonMail/comments/195is7m/proton_team_please_fix_theme_icons/
> 
> Yeah indeed. The team has been looking into designing a Material You Icon for several months now. How hard. Even rewriting the whole app was easier.

its two lines to add the icons lol
image

**Comment by Extravi** [comment]
> > > i found this from a month ago https://www.reddit.com/r/ProtonMail/comments/195is7m/proton_team_please_fix_theme_icons/
> > 
> > 
> > Yeah indeed. The team has been looking into designing a Material You Icon for several months now. How hard. Even rewriting the whole app was easier.
> 
> its two lines to add the icons lol image

https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by asudox** [comment]
> > > > i found this from a month ago https://www.reddit.com/r/ProtonMail/comments/195is7m/proton_team_please_fix_theme_icons/
> > > 
> > > 
> > > Yeah indeed. The team has been looking into designing a Material You Icon for several months now. How hard. Even rewriting the whole app was easier.
> > 
> > its two lines to add the icons lol image
> 
> https://developer.android.com/about/versions/13/features#themed-app-icons

According to some guy on reddit that replied on my post, the other apps apparently got their Material You Icons last week on the beta release. So I guess we can expect to see it for the mail app soon as well?

**Pull request closed without merging**
