### PR TITLE
Adds Bug & Feature Request Issue Templates

### PR DESCRIPTION
**Pull request by darigovresearch**
Uses default GitHub issue templates for Bug and Feature Requests and adapts it to be relevant to the repository.

Followed instructions in the documentation - https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

Would resolve issue #23 if merged.

### CODE REVIEW

**Comment by darigovresearch** [comment]
Is there anything else needed on our side to merge this pull request?

Would be happy to make any additional changes or merge it ourselves if added as a collaborator to the repository!

**Comment by FireMasterK** [comment]
ProtonMail has a private gitlab server where they commit stuff. This GitHub repository is just a read only mirror which is updated every release. This is really goes against the spirit of open source and I have no clue why they have taken this approach. This really seems more like a marketing tactic (it worked quite well) rather than rather them actually wanting to contribute to the open source community. While I was excited when the app went open source, I no longer feel excited as they don't respond to GitHub issue and pull requests in a timely manner, which is what an open source project should be good at: CONTRIBUTIONS by anyone.

If anyone from ProtonMail reads this, compare this repository with https://github.com/mullvad/mullvadvpn-app and you'll see the huge difference.

**Comment by bartbutler** [comment]
@FireMasterK, you're quite right that this is a mirrored repository, and we also haven't been very responsive to community issues and PRs. There have been many internal discussions about how to facilitate this while still preserving the ability to have private branches and discussion, which I think is important for several reasons:

1. Facilitating discussions and PRs involving not-yet-public information regarding features and roadmaps
2. Embargoing security fixes until just after public deployment
3. Protecting employees from verbal abuse from the peanut gallery of the Internet (this does happen)
4. Not being dependent on third party services for deployment/CI/etc (in this case, Github)

The primary reason that making all our clients are open-source is imperative is to facilitate third-party security audits. Any code that we release to the public makes it here. Community contributions are absolutely a close second and we do want to encourage these but we honestly haven't figure out how to do this efficiently yet, sorry. I'll ping the team about this PR @darigovresearch .

**Comment by fardavide** [comment]
@FireMasterK We're sorry to have reserved a very little time to this repo maintenance, but given some organizational changes and improvements happened recently in the team, allocating more time was just impossible.

Unluckily, being this repository a mirror of our private one*, it's not easy and straightforward to integrate PRs into the code-base; obviously this is something that **_HAS to be done, but just requires us a little coordination with the other teams_**, with the aim to preserve as many details as possible** ( authority & co. )

*it is not private because we wanna hide something :) but for 2 simple reasons:
* That **would required us migrate from GitLab**, where we have all our tools and virtual machines that runs CI, Jira integration and a lot of settings ( branch naming regex validation, roles, approval rules, etc. )
* Having a private server provide us **another layer of protection** from malicious attacks

**_Due to our process contributors can expect us to preserve the authorship, but signatures might be lost._

---

Said that, I thank @bartbutler for the reminder, @darigovresearch for the PR, and announce that **_we already started to coordinate internally for deal with it_** - **_probably you won't receive a direct tangible feedback, since changes will hit here only once the code hit production state_** and I'm not sure if physically approving this PR on GitHub will keep us save from future conflicts during the syncing process.
Anyway I'll provide you updates ASAP

**Comment by fardavide** [comment]
This has been merged on main branch of GitLab repository.
Changes will be visible here once it reaches production.

Commit ref: `9e989c51`

**Pull request closed without merging**
