### PR TITLE
refactor: Avoid exposing mutable flows for consumers

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by nafoiw1410** [comment]
Why hasn't Proton.me updated the source code on here for half a year now

**Comment by nicola-taylor** [comment]
Seconding @nafoiw1410 's question. Has Proton Mail for Android gone closed-source? Current (and only) branch seems way out of date compared to what's on the Play Store.

**Comment by hristogochev** [comment]
The lack of communication is concerning.

**Comment by mcodax** [comment]
https://github.com/ProtonMail/proton-mail-android/pull/224#issuecomment-1833624990

This probably answers your questions.

**Comment by Gitchick57** [comment]
Does anyone know when there will be an updated APK for Proton Mail on GitHub?



Apr 28, 2024, 7:38 PM by ***@***.***:

**Comment by nafoiw1410** [comment]
Doesn't seems like it makes sense "closing down the repo" for collaboration lol. Isn't the whole point of a public git repo for collaborating?

**Pull request closed without merging**
