### PR TITLE
Issue #67 - Disable swiping actions - feature added

### PR DESCRIPTION
**Pull request by LeTempus**
At this stage, the feature works as wanted and expected. The only downside is that the app needs to be closed and reopened in order to see the change applied in the MailboxActivity. But I think it is good enough for the users wanting to disable the swiping gestures.
Affected: EditSettingsItemActivity.kt - MailboxActivity.kt - SettingsEnum.kt - User.kt - Constants.kt - edit_settings_structure.json

Feel free to tell if you'd like something changed and/or improved.

### CODE REVIEW

**Comment by LeTempus** [comment]
Changed the commit message content as I realized the title was not compliant with the Proton Guidelines. Also added strings.xml to the list of files affected by the changes.

**Comment by LeTempus** [comment]
Hi @marinomeneghel, @4face-studi0, I hope I am not bothering you too much with this. I was just trying to know if this feature had good chances to be added later down the line upstream. As I have understood, this repository is a mirror and including changes upstream requires some coordination etc. So I totally understand if this will take some time, I am just trying to figure out the sentiment on it being a change that could be included at some point. 

Thanks for your time! :smile:

**Comment by marinomeneghel** [comment]
@LeTempus thanks for raising this PR! 

The current live version of the app is only receiving critical bug fixes while we work on the next major revision, we will add this to our feature backlog to prioritize it once the next major revision releases. The functionality you are proposing sounds like a good enhancement, so it is indeed something we will evaluate including.

**Comment by darigovresearch** [comment]
One of the first things that many users do to reduce latency on their devices is to disable swiping/animated actions, would be happy to see this in the next release if easy to implement thanks to the pull request. If some of this implementation is taken on board would be nice to see it credited like how GitHub Desktop does in their changelog for community contributions if @LeTempus would like to be credited.

This may also encourage other community led contributions like this one in the future

**Comment by marinomeneghel** [comment]
We didn't have a chance to prioritise this yet, but it is a feature that we are tracking in our backlog and will get worked on at some point.

**Pull request closed without merging**
