### PR TITLE
Dark Mode for Mailbox

### PR DESCRIPTION
**Pull request by gahfy**
Use `proton-core:presentation` colors for mailbox to make it displayable in dark mode.

This affect the light mode with minor color changes:

This is a proposition of work for #32

### CODE REVIEW

**Comment by gahfy** [comment]
* [x] ~Labels are broken, need to adapt them to dark mode~
* [x] ~"No message" text appears dark on dark, need to update~
* [x] ~Update from scroll to bottom shows a dirty white background space, need to fix~

**Comment by darigovresearch** [comment]
If the pull request resolves the issue, it should be merged if possible. Can anyone from the Protonmail team advise if there is anything else needed to merge this pull request?

**Comment by darigovresearch** [comment]
@marinomeneghel could you please advise on the above?

**Comment by marinomeneghel** [comment]
Hey @darigovresearch , thanks for bringing our attention to this and thanks @gahfy for raising this PR! 

The current situation is, we do have few moving pieces regarding theming internally and we don't (yet!) have a friendly process to merge code from GitHub to the internal repo.

To keep this lightweight, I would suggest to wait for the theming changes to make it to GitHub and re-evaluate the need for this PR to be merged then.

**Comment by sawft99** [comment]
If there's a dark theme now and #32 is closed should this be closed then?

**Pull request closed without merging**
